apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
labels:
  type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/wordpress/"

